# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

cache_key : &cache_key v10-microservice-infrastructure-{{ .Branch }}-{{ checksum "build.gradle" }}

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: *cache_key

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: *cache_key
        
      # run build
      - run: gradle build -DcertificateCheck=false
      
      # store build jar files
      - store_artifacts:
          path: ~/repo/auth-server
       
      - setup_remote_docker

      - run:
          name: Install Docker Compose
          command: | 
            set -x
            sudo curl -L https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - deploy:
          name: Build and push Docker image
          command: |
            #TAG="0.1.${CIRCLE_BUILD_NUM}"
            TAG="latest"
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            
            cd ~/repo/auth-server
            docker build -t maltor/auth-server:$TAG .
            docker push maltor/auth-server:$TAG
            
            cd ~/repo/config-server
            docker build -t maltor/config-server:$TAG .
            docker push maltor/config-server:$TAG
            
            cd ~/repo/discovery-server
            docker build -t maltor/discovery-server:$TAG .
            docker push maltor/discovery-server:$TAG
            
            cd ~/repo/edge-server
            docker build -t maltor/edge-server:$TAG .
            docker push maltor/edge-server:$TAG
           
            cd ~/repo/resource-server
            docker build -t maltor/resource-server:$TAG .
            docker push maltor/resource-server:$TAG 
