version: "3"
services:

  #######################################
  #####       manager1               ####
  #######################################
    
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - shopnet
  
  #######################################
  #####    infrastructure1           ####
  #######################################
  
#  shop-db:
#    image: mysql:5.7
#    deploy:
#      placement:
#        constraints: [node.hostname == infrastructure1]
#    ports:
#     - "4001:3306"
#    networks:
#     - shopnet 
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: shop
#      MYSQL_USER: shop
#      MYSQL_PASSWORD: shop
  
  rabbitmq:
    image: rabbitmq:3.6-management
    deploy:
      placement:
        constraints: [node.hostname == infrastructure1]
    ports:
     - "15672:15672"
    networks:
     - shopnet  
  
  #server 
  config-server:
    image: maltor/config-server
    deploy:
      placement:
        constraints: [node.hostname == infrastructure1]
      resources:
        limits:
          memory: 256M
    ports:
     - "8888:8888"
    networks:
     - shopnet
  
  discovery-server:
    image: maltor/discovery-server
    deploy:
      placement:
        constraints: [node.hostname == infrastructure1]    
      resources:
        limits:
          memory: 256M
    ports:
     - "8761:8761"
    networks:
     - shopnet
      
  auth-server:
    image: maltor/auth-server
    deploy:
      placement:
        constraints: [node.hostname == infrastructure1]    
      resources:
        limits:
          memory: 128M
    ports:
     - "9999:9999"
    networks:
     - shopnet
       
  resource-server:
    image: maltor/resource-server
    deploy:
      placement:
        constraints: [node.hostname == infrastructure1]    
      resources:
       limits:
         memory: 128M
    ports:
     - "9090:9090"
    networks:
     - shopnet   

  edge-server:
    image: maltor/edge-server
    deploy:
      placement:
        constraints: [node.hostname == infrastructure1]    
      resources:
        limits:
          memory: 256M
    ports:
     - "8765:8765"
    networks:
     - shopnet