server:
  port: 8888
  
info:
  component: Config Server

spring:
  cloud:
    config:
      #server.git.uri: https://github.com/maltorpro/config-shop-demo
      server.git.uri: file:///${user.home}/workspace/config-shop-demo
      label: master

  rabbitmq:
    host: localhost
    port: 5672

---
# For deployment in Docker containers
spring:
  profiles: docker


spring.rabbitmq.host: rabbitmq

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    