server:
  port: 8888
  
info:
  component: Config Server

spring:
  cloud:
    config:
      server.git.uri: https://raw.githubusercontent.com/maltorpro/DeliveryServer/master/config

  rabbitmq:
    host: localhost
    port: 5672

---
# For deployment in Docker containers
spring:
  profiles: docker


spring.rabbitmq.host: rabbitmq

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    