server:
  port: 8888
  ssl:
    key-store: classpath:cert.p12
    key-store-password: c9xZpx
  http2.enable: true
  
info:
  component: Config Server

spring:
  cloud:
    config:
      #Git server
      #server.git.uri: https://github.com/maltorpro/config-shop-demo
      #Linux Mac OS
      ##server.git.uri: file://${user.home}/Documents/workspace/config-shop-demo
      #Windows
      #server.git.uri: file:///${user.home}/workspace/config-shop-demo
      server:
        git:
          uri: file://${user.home}/Documents/workspace/config-shop-demo

  rabbitmq:
    host: localhost
    port: 5672

---
# For deployment in Docker containers
spring:
  profiles: docker
  rabbitmq.host: rabbitmq
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maltorpro/config-shop-demo
      label: master

---
# For deployment in Docker containers
spring:
  profiles: test
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maltorpro/config-shop-demo
      label: master 